version: "3.8"

services:
  app:
    container_name: app-prod
    image: app-prod
    build: .
    env_file:
      - ./.env.production
    volumes:
      - .:/usr/src/app
    ports:
        - '80:80'  
  