name: ci

on:
    push:
        branches:
            - main
            - dev
            - master
    pull_request:
        branches:
            - main
            - dev
            - master

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node env
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: clean cache
              run: npm cache clean --force
           
            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Run Build
              run: npm run build:prod
              env:
                  CI: false